services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: scms-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SCMS@SqlServer2026!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/SCMS.API/Dockerfile
    container_name: scms-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=SCMSDb;User Id=sa;Password=SCMS@SqlServer2026!;TrustServerCertificate=True;MultipleActiveResultSets=True"
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

  web:
    build:
      context: .
      dockerfile: src/SCMS.Web/Dockerfile
    container_name: scms-web
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ApiSettings__BaseUrl: "http://api:8080"
    depends_on:
      - api

volumes:
  sqlserver_data:
